[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "src/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"